version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "matteovivona"
    reviewers:
      - "matteovivona"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "matteovivona"
    reviewers:
      - "matteovivona"
  
