name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  NPM_CONFIG_PROVENANCE: true
  PNPM_VERSION: 10.4.1
  NODE_VERSION: 20

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        name: Install Node
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        name: Install pnpm
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.DUCKTORS_PAT }}
          NPM_TOKEN: ${{ secrets.DUCKTORS_NPM_TOKEN }}
        run: pnpm semantic-release
