name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  NPM_CONFIG_PROVENANCE: true
  PNPM_VERSION: 10.4.1
  NODE_VERSION: 20

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        name: Checkout
        with:
          persist-credentials: false

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        name: Install Node
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        name: Install pnpm
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.DUCKTORS_PAT }}
          NPM_TOKEN: ${{ secrets.DUCKTORS_NPM_TOKEN }}
        run: pnpm semantic-release
