name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3
        name: Install Node
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.DUCKTORS_PAT }}
          NPM_TOKEN: ${{ secrets.DUCKTORS_NPM_TOKEN }}
        run: npx semantic-release
